Use new resolve API to support TypeDoc v0.24
Gerrit0/typedoc-plugin-mdn-links pull request #8
Opened 2023-03-07 11:09 UTC by ocavue

- Update typedoc version ranges
- Use new resolver API

2023-03-08 02:01 UTC, Gerrit0 requested changes

2023-03-08 02:01 UTC, Gerrit0 commented on src/index.ts
> +        const name = declaration.symbolReference?.path?.[0].path;
This isn't quite right, should be:

```ts
  const name = ref.symbolReference?.path
                ?.map((path) => path.path)
                .join(".");
```

2023-03-08 02:36 UTC, ocavue commented on src/index.ts
> +        const name = declaration.symbolReference?.path?.[0].path;
Fixed

2023-03-08 02:36 UTC, ocavue commented on package.json
> +    "typedoc": ">= 0.22.14 || >= 0.23.26 || 0.24.x"
Fixed

2023-03-10 02:19 UTC, merged

2023-03-10 02:19 UTC, Gerrit0 commented
Thanks!